--- Makefile
+++ Makefile
@@ -37,7 +37,7 @@ dist: clean
 	@echo creating dist tarball
 	@mkdir -p tabbed-${VERSION}
 	@cp -R LICENSE Makefile README config.def.h config.mk \
-		tabbed.1 arg.h ${SRC} tabbed-${VERSION}
+		tabbed.1 arg.h icon.h ${SRC} tabbed-${VERSION}
 	@tar -cf tabbed-${VERSION}.tar tabbed-${VERSION}
 	@gzip tabbed-${VERSION}.tar
 	@rm -rf tabbed-${VERSION}
